# Generated by Django 3.2.13 on 2022-06-22 17:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0002_settings_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='NewsSetting',
        ),
    ]
